// Mapa de livros em inglês para abreviações portuguesas (para API)
const BOOK_ABBREVIATIONS: Record<string, string> = {
  Genesis: "gn",
  Exodus: "ex",
  Leviticus: "lv",
  Numbers: "nm",
  Deuteronomy: "dt",
  Joshua: "js",
  Judges: "jz",
  Ruth: "rt",
  "1 Samuel": "1sm",
  "2 Samuel": "2sm",
  "1 Kings": "1rs",
  "2 Kings": "2rs",
  "1 Chronicles": "1cr",
  "2 Chronicles": "2cr",
  Ezra: "ed",
  Nehemiah: "ne",
  Esther: "et",
  Job: "job",
  Psalms: "sl",
  Proverbs: "pv",
  Ecclesiastes: "ec",
  "Song of Solomon": "ct",
  Isaiah: "is",
  Jeremiah: "jr",
  Lamentations: "lm",
  Ezekiel: "ez",
  Daniel: "dn",
  Hosea: "os",
  Joel: "jl",
  Amos: "am",
  Obadiah: "ob",
  Jonah: "jn",
  Micah: "mq",
  Nahum: "na",
  Habakkuk: "hc",
  Zephaniah: "sf",
  Haggai: "ag",
  Zechariah: "zc",
  Malachi: "ml",
  Matthew: "mt",
  Mark: "mc",
  Luke: "lc",
  John: "jo",
  Acts: "at",
  Romans: "rm",
  "1 Corinthians": "1co",
  "2 Corinthians": "2co",
  Galatians: "gl",
  Ephesians: "ef",
  Philippians: "fp",
  Colossians: "cl",
  "1 Thessalonians": "1ts",
  "2 Thessalonians": "2ts",
  "1 Timothy": "1tm",
  "2 Timothy": "2tm",
  Titus: "tt",
  Philemon: "fm",
  Hebrews: "hb",
  James: "tg",
  "1 Peter": "1pe",
  "2 Peter": "2pe",
  "1 John": "1jo",
  "2 John": "2jo",
  "3 John": "3jo",
  Jude: "jd",
  Revelation: "ap",
};

/**
 * Obtém a abreviação de um livro bíblico pelo nome em inglês
 */
export function getBookAbbreviation(bookName: string): string | null {
  return BOOK_ABBREVIATIONS[bookName] || null;
}
