// Dados dos livros da Bíblia
import { BibleBook } from "../types";

export const BIBLE_BOOKS_DATA: BibleBook[] = [
  { name: "Genesis", ptName: "Gênesis", chapters: 50 },
  { name: "Exodus", ptName: "Êxodo", chapters: 40 },
  { name: "Leviticus", ptName: "Levítico", chapters: 27 },
  { name: "Numbers", ptName: "Números", chapters: 36 },
  { name: "Deuteronomy", ptName: "Deuteronômio", chapters: 34 },
  { name: "Joshua", ptName: "Josué", chapters: 24 },
  { name: "Judges", ptName: "Juízes", chapters: 21 },
  { name: "Ruth", ptName: "Rute", chapters: 4 },
  { name: "1 Samuel", ptName: "1 Samuel", chapters: 31 },
  { name: "2 Samuel", ptName: "2 Samuel", chapters: 24 },
  { name: "1 Kings", ptName: "1 Reis", chapters: 22 },
  { name: "2 Kings", ptName: "2 Reis", chapters: 25 },
  { name: "1 Chronicles", ptName: "1 Crônicas", chapters: 29 },
  { name: "2 Chronicles", ptName: "2 Crônicas", chapters: 36 },
  { name: "Ezra", ptName: "Esdras", chapters: 10 },
  { name: "Nehemiah", ptName: "Neemias", chapters: 13 },
  { name: "Esther", ptName: "Ester", chapters: 10 },
  { name: "Job", ptName: "Jó", chapters: 42 },
  { name: "Psalms", ptName: "Salmos", chapters: 150 },
  { name: "Proverbs", ptName: "Provérbios", chapters: 31 },
  { name: "Ecclesiastes", ptName: "Eclesiastes", chapters: 12 },
  { name: "Song of Solomon", ptName: "Cantares", chapters: 8 },
  { name: "Isaiah", ptName: "Isaías", chapters: 66 },
  { name: "Jeremiah", ptName: "Jeremias", chapters: 52 },
  { name: "Lamentations", ptName: "Lamentações", chapters: 5 },
  { name: "Ezekiel", ptName: "Ezequiel", chapters: 48 },
  { name: "Daniel", ptName: "Daniel", chapters: 12 },
  { name: "Hosea", ptName: "Oséias", chapters: 14 },
  { name: "Joel", ptName: "Joel", chapters: 3 },
  { name: "Amos", ptName: "Amós", chapters: 9 },
  { name: "Obadiah", ptName: "Obadias", chapters: 1 },
  { name: "Jonah", ptName: "Jonas", chapters: 4 },
  { name: "Micah", ptName: "Miquéias", chapters: 7 },
  { name: "Nahum", ptName: "Naum", chapters: 3 },
  { name: "Habakkuk", ptName: "Habacuque", chapters: 3 },
  { name: "Zephaniah", ptName: "Sofonias", chapters: 3 },
  { name: "Haggai", ptName: "Ageu", chapters: 2 },
  { name: "Zechariah", ptName: "Zacarias", chapters: 14 },
  { name: "Malachi", ptName: "Malaquias", chapters: 4 },
  { name: "Matthew", ptName: "Mateus", chapters: 28 },
  { name: "Mark", ptName: "Marcos", chapters: 16 },
  { name: "Luke", ptName: "Lucas", chapters: 24 },
  { name: "John", ptName: "João", chapters: 21 },
  { name: "Acts", ptName: "Atos", chapters: 28 },
  { name: "Romans", ptName: "Romanos", chapters: 16 },
  { name: "1 Corinthians", ptName: "1 Coríntios", chapters: 16 },
  { name: "2 Corinthians", ptName: "2 Coríntios", chapters: 13 },
  { name: "Galatians", ptName: "Gálatas", chapters: 6 },
  { name: "Ephesians", ptName: "Efésios", chapters: 6 },
  { name: "Philippians", ptName: "Filipenses", chapters: 4 },
  { name: "Colossians", ptName: "Colossenses", chapters: 4 },
  { name: "1 Thessalonians", ptName: "1 Tessalonicenses", chapters: 5 },
  { name: "2 Thessalonians", ptName: "2 Tessalonicenses", chapters: 3 },
  { name: "1 Timothy", ptName: "1 Timóteo", chapters: 6 },
  { name: "2 Timothy", ptName: "2 Timóteo", chapters: 4 },
  { name: "Titus", ptName: "Tito", chapters: 3 },
  { name: "Philemon", ptName: "Filemom", chapters: 1 },
  { name: "Hebrews", ptName: "Hebreus", chapters: 13 },
  { name: "James", ptName: "Tiago", chapters: 5 },
  { name: "1 Peter", ptName: "1 Pedro", chapters: 5 },
  { name: "2 Peter", ptName: "2 Pedro", chapters: 3 },
  { name: "1 John", ptName: "1 João", chapters: 5 },
  { name: "2 John", ptName: "2 João", chapters: 1 },
  { name: "3 John", ptName: "3 João", chapters: 1 },
  { name: "Jude", ptName: "Judas", chapters: 1 },
  { name: "Revelation", ptName: "Apocalipse", chapters: 22 },
];
